import React from 'react';
export default props =>
//PARA ENCAPSULAR ELEMENTOS ADJACENTES USAMOS UMA DIV, UMA TAG "FANTASMA" (SEM NADA DENTRO), OU COLCHETES COM VÍRGULA APÓS OS ELEMENTOS
[
<h1>Parte 1</h1>,
<h2>Parte 2</h2>
]